import { LegalPage, type LegalBlock } from "@/components/LegalPage";

const blocks: LegalBlock[] = [
    { type: "h2", text: "Interpretation and Definitions" },
    { type: "h3", text: "Interpretation" },
    { type: "p", text: "The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural." },
    { type: "h3", text: "Definitions" },
    { type: "p", text: "For the purposes of this Privacy Policy:" },
    {
        type: "dl", items: [
            { term: "Account", text: "means a unique account created for you to access our Service or parts of our Service." },
            { term: "Affiliate", text: "means an entity that controls, is controlled by, or is under common control with a party, where \"control\" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority." },
            { term: "Company", text: "(referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Privacy Policy) refers to Weinix, B-907, Unicus Shyamal, Shyamal Cross Road, Ahmedabad, Gujarat, India 380015." },
            { term: "Cookies", text: "are small files that are placed on your computer, mobile device, or any other device by a website, containing the details of your browsing history on that website, among its many uses." },
            { term: "Country", text: "refers to: Gujarat, India." },
            { term: "Device", text: "means any device that can access the Service, such as a computer, a cell phone, or a digital tablet." },
            { term: "Personal Data", text: "(or \"Personal Information\") is any information that relates to an identified or identifiable individual. We use \"Personal Data\" and \"Personal Information\" interchangeably unless a law uses a specific term." },
            { term: "Service", text: "refers to the Website." },
            { term: "Service Provider", text: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used." },
            { term: "Usage Data", text: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
            { term: "Website", text: "refers to Weinix, accessible from https://www.weinix.com/." },
            { term: "You", text: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." },
        ]
    },

    { type: "h2", text: "Collecting and Using Your Personal Data" },
    { type: "h3", text: "Personal Data" },
    { type: "p", text: "While using Our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:" },
    { type: "ul", items: ["Email address", "First name and last name", "Phone number"] },

    { type: "h3", text: "Usage Data" },
    { type: "p", text: "Usage Data is collected automatically when using the Service." },
    { type: "p", text: "Usage Data may include information such as Your Device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data." },
    { type: "p", text: "When you access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device's unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers, and other diagnostic data." },
    { type: "p", text: "We may also collect information that your browser sends whenever you visit Our Service or when you access the Service by or through a mobile device." },

    { type: "h3", text: "Tracking Technologies and Cookies" },
    { type: "p", text: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies we use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies we use may include:" },
    {
        type: "dl", items: [
            { term: "Cookies or Browser Cookies.", text: "A cookie is a small file placed on Your Device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service." },
            { term: "Web Beacons.", text: "Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity)." },
        ]
    },
    { type: "p", text: "Cookies can be \"Persistent\" or \"Session\" Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser." },
    { type: "p", text: "Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with your consent. You can withdraw or change your consent at any time using our cookie preferences tool (if available) or through your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal." },
    { type: "p", text: "We use both Session and Persistent Cookies for the purposes set out below:" },
    { type: "card", title: "Necessary / Essential Cookies", rows: [
        { label: "Type", value: "Session Cookies" },
        { label: "Administered by", value: "Us" },
        { label: "Purpose", value: "These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that you have asked for cannot be provided, and we only use these Cookies to provide you with those services." },
    ] },
    { type: "card", title: "Cookies Policy / Notice Acceptance Cookies", rows: [
        { label: "Type", value: "Persistent Cookies" },
        { label: "Administered by", value: "Us" },
        { label: "Purpose", value: "These Cookies identify if users have accepted the use of cookies on the Website." },
    ] },
    { type: "card", title: "Functionality Cookies", rows: [
        { label: "Type", value: "Persistent Cookies" },
        { label: "Administered by", value: "Us" },
        { label: "Purpose", value: "These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the Website." },
    ] },
    { type: "p", text: "For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy." },

    { type: "h3", text: "Use of Your Personal Data" },
    { type: "p", text: "The Company may use Personal Data for the following purposes:" },
    {
        type: "dl", items: [
            { term: "To provide and maintain our Service,", text: "including monitoring the usage of our Service." },
            { term: "To manage Your Account:", text: "to manage your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user." },
            { term: "For the performance of a contract:", text: "the development, compliance, and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with Us through the Service." },
            { term: "To contact You:", text: "To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation." },
            { term: "To provide you with news, special offers, and general information", text: "about other goods, services, and events that we offer that are similar to those that you have already purchased or inquired about, unless you have opted not to receive such information." },
            { term: "To manage Your requests:", text: "To attend to and manage Your requests to Us." },
            { term: "For business transfers:", text: "We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred." },
            { term: "For other purposes:", text: "We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your experience." },
        ]
    },
    { type: "p", text: "We may share Your Personal Data in the following situations:" },
    {
        type: "dl", items: [
            { term: "With Service Providers:", text: "We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You." },
            { term: "For business transfers:", text: "We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company." },
            { term: "With Affiliates:", text: "We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners, or other companies that we control or that are under common control with Us." },
            { term: "With business partners:", text: "We may share Your Personal Data with our business partners to offer you certain products, services, or promotions." },
            { term: "With other users:", text: "If Our Service offers public areas, when you share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside." },
            { term: "With Your consent:", text: "We may disclose Your Personal Data for any other purpose with Your consent." },
        ]
    },

    { type: "h2", text: "Retention of Your Personal Data" },
    { type: "p", text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies." },
    { type: "p", text: "Where possible, we apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods (\"up to\"), and we may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:" },

    { type: "h3", text: "Account Information" },
    { type: "ul", items: ["User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes."] },

    { type: "h3", text: "Customer Support Data" },
    { type: "ul", items: [
        "Support tickets and correspondence: up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims.",
        "Chat transcripts: up to 24 months for quality assurance and staff training purposes.",
    ] },

    { type: "h3", text: "Usage Data" },
    { type: "ul", items: [
        "Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.",
        "Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.",
    ] },
    { type: "p", text: "Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance." },
    { type: "p", text: "We may retain Personal Data beyond the periods stated above for different reasons:" },
    {
        type: "dl", items: [
            { term: "Legal obligation:", text: "We are required by law to retain specific data (e.g., financial records for tax authorities)." },
            { term: "Legal claims:", text: "Data is necessary to establish, exercise, or defend legal claims." },
            { term: "Your explicit request:", text: "You ask us to retain specific information." },
            { term: "Technical limitations:", text: "Data exists in backup systems that are scheduled for routine deletion." },
        ]
    },
    { type: "p", text: "You may request information about how long we will retain Your Personal Data by contacting Us." },
    { type: "p", text: "When retention periods expire, we securely delete or anonymize Personal Data according to the following procedures:" },
    {
        type: "dl", items: [
            { term: "Deletion:", text: "Personal Data is removed from our systems and no longer actively processed." },
            { term: "Backup retention:", text: "Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance." },
            { term: "Anonymization:", text: "In some cases, we convert Personal Data into anonymous statistical data that cannot be linked back to you. This anonymized data may be retained indefinitely for research and analytics." },
        ]
    },

    { type: "h2", text: "Transfer of Your Personal Data" },
    { type: "p", text: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction." },
    { type: "p", text: "Where required by applicable law, we will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place, including the security of Your data and other personal information." },

    { type: "h2", text: "Delete Your Personal Data" },
    { type: "p", text: "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You." },
    { type: "p", text: "Our Service may give You the ability to delete certain information about You from within the Service." },
    { type: "p", text: "You may update, amend, or delete your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us." },
    { type: "p", text: "Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so." },

    { type: "h2", text: "Disclosure of Your Personal Data" },
    { type: "h3", text: "Business Transactions" },
    { type: "p", text: "If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy." },
    { type: "h3", text: "Law enforcement" },
    { type: "p", text: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency)." },
    { type: "h3", text: "Other legal requirements" },
    { type: "p", text: "The Company may disclose Your Personal Data in good faith belief that such action is necessary to:" },
    { type: "ul", items: [
        "Comply with a legal obligation",
        "Protect and defend the rights or property of the Company",
        "Prevent or investigate possible wrongdoing in connection with the Service",
        "Protect the personal safety of Users of the Service or the public",
        "Protect against legal liability",
    ] },

    { type: "h2", text: "Security of Your Personal Data" },
    { type: "p", text: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially reasonable means to protect Your Personal Data, we cannot guarantee its absolute security." },

    { type: "h2", text: "Children's Privacy" },
    { type: "p", text: "Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 16 without verification of parental consent, we take steps to remove that information from our servers." },
    { type: "p", text: "If we need to rely on consent as a legal basis for processing your information, and your country requires consent from a parent, we may require your parent's consent before we collect and use that information." },

    { type: "h2", text: "Links to Other Websites" },
    { type: "p", text: "Our Service may contain links to other websites that are not operated by Us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit." },
    { type: "p", text: "We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services." },

    { type: "h2", text: "Changes to this Privacy Policy" },
    { type: "p", text: "We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page." },
    { type: "p", text: "We will let you know via email and/or a prominent notice on Our Service, prior to the change becoming effective, and update the \"Last updated\" date at the top of this Privacy Policy." },
    { type: "p", text: "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page." },

    { type: "h2", text: "Contact Us" },
    { type: "p", text: "If you have any questions about this Privacy Policy, you can contact us:" },
    { type: "ul", items: ["By email: contact@re-verse.in", "By phone: 9898458583"] },
];

export default function PrivacyPolicyPage() {
    return (
        <LegalPage
            badge="Legal"
            title="Privacy Policy"
            lastUpdated="July 20, 2026"
            intro={[
                "This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.",
                "We use Your Personal Data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.",
            ]}
            blocks={blocks}
        />
    );
}
