import { defineField, defineType } from "sanity";
import TinyMCEInput from "../components/TinyMCEInput";

export default defineType({
  name: "post",
  title: "Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "title", title: "Title", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({ name: "subtitle", title: "Subtitle", type: "string", group: "content" }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      group: "content",
      description: "Short summary shown on the blog list card.",
      validation: (r) => r.max(240),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      group: "content",
      description: "Primary blog category, e.g. \"Sustainability\", \"Industry Insights\".",
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      group: "content",
      to: [{ type: "author" }],
      validation: (r) => r.required(),
    }),
    defineField({
      name: "mainImage",
      title: "Main image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        defineField({ name: "alt", title: "Alt text", type: "string", description: "Describes the image for accessibility & SEO." }),
        defineField({ name: "caption", title: "Caption", type: "string", description: "Optional caption shown under the hero image." }),
      ],
      validation: (r) => r.required(),
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({ name: "readTime", title: "Read time", type: "string", group: "content", description: 'e.g. "9 min read"' }),
    defineField({ name: "publishedAt", title: "Published at", type: "datetime", group: "content", validation: (r) => r.required() }),
    defineField({ name: "updatedAt", title: "Updated at", type: "datetime", group: "content" }),
    defineField({
      name: "metaTitle",
      title: "Meta title",
      type: "string",
      group: "seo",
      description: "Overrides the page <title> and OG/Twitter title shown in search results and social shares. Falls back to the post title if left blank.",
      validation: (r) => r.max(70).warning("Search engines typically truncate titles beyond ~60-70 characters."),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta description",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Overrides the meta description shown in search results and social shares. Falls back to the excerpt/subtitle if left blank.",
      validation: (r) => r.max(160).warning("Search engines typically truncate descriptions beyond ~155-160 characters."),
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "text",
      group: "content",
      description: "Full rich-text editor (headings, fonts, colors, alignment, tables, images, etc).",
      components: { input: TinyMCEInput },
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "subtitle", media: "mainImage" },
  },
});
